#!/usr/bin/env python3
"""Interactive setup wizard for Pulse RAG.

Usage:  python setup.py
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import yaml


# ── helpers ──────────────────────────────────────────────────────────────────

def _ask(prompt: str, default: str | None = None) -> str:
    hint = f" [{default}]" if default is not None else ""
    raw = input(f"{prompt}{hint}: ").strip()
    return raw if raw else (default or "")


def _ask_choice(prompt: str, choices: list[str], default: str) -> str:
    formatted = "/".join(f"[{c}]" if c == default else c for c in choices)
    while True:
        val = _ask(f"{prompt} ({formatted})", default)
        if val in choices:
            return val
        print(f"  Please enter one of: {', '.join(choices)}")


def _ask_yn(prompt: str, default: bool = True) -> bool:
    hint = "Y/n" if default else "y/N"
    raw = input(f"{prompt} [{hint}]: ").strip().lower()
    if not raw:
        return default
    return raw in ("y", "yes")


def _section(title: str) -> None:
    pad = max(0, 48 - len(title))
    print(f"\n── {title} {'─' * pad}")


# ── collectors ───────────────────────────────────────────────────────────────

def _collect_llm() -> dict:
    provider = _ask_choice("Provider", ["ollama", "openai", "custom"], "ollama")
    if provider == "ollama":
        return {
            "provider": "ollama",
            "model": _ask("  Model", "qwen3:8b"),
            "base_url": _ask("  Base URL", "http://localhost:11434"),
            "temperature": 0,
        }
    if provider == "openai":
        return {
            "provider": "openai",
            "model": _ask("  Model", "gpt-4o-mini"),
            "temperature": 0,
        }
    return {
        "provider": "custom",
        "model": _ask("  Model name"),
        "base_url": _ask("  Base URL (e.g. http://localhost:8317/v1)"),
        "api_key": _ask("  API key", "EMPTY"),
        "temperature": 0,
    }


def _collect_api_keys() -> dict[str, str]:
    keys: dict[str, str] = {}
    print("  Leave blank to skip.")
    for key, hint in [
        ("TAVILY_API_KEY", "web search plugin"),
        ("HUGGINGFACEHUB_API_TOKEN", "optional"),
        ("OPENAI_API_KEY", "only if using OpenAI provider"),
    ]:
        val = _ask(f"  {key} ({hint})", "")
        if val:
            keys[key] = val
    return keys


def _collect_knowledge_bases() -> list[dict]:
    kbs: list[dict] = []
    print("  Add at least one knowledge base.")
    while True:
        idx = len(kbs) + 1
        print(f"\n  KB #{idx}")
        name = _ask("    Name (e.g. english)", f"kb{idx}")
        data_dir = _ask("    Data directory (.txt files)", f"data/{name}")
        index_path = _ask("    Index save path", f"faiss_index_{name}")
        tool_name = _ask("    Tool name for the agent", f"retrieve_{name}")
        tool_desc = _ask("    Tool description (what this KB covers)")
        url_prefix = _ask("    Source URL prefix (optional)", "")

        kb: dict = {
            "name": name,
            "data_dir": data_dir,
            "index_path": index_path,
            "tool_name": tool_name,
            "tool_description": tool_desc,
        }
        if url_prefix:
            kb["url_prefix"] = url_prefix
        kbs.append(kb)

        if not _ask_yn("  Add another knowledge base?", False):
            break
    return kbs


def _collect_system_prompt() -> str | None:
    existing = Path("config/system_prompt.txt")
    if existing.exists() and _ask_yn("  Keep existing system_prompt.txt?", True):
        return None
    print("  Paste your system prompt. Press Enter on an empty line to finish:")
    lines: list[str] = []
    while True:
        line = input()
        if not line:
            break
        lines.append(line)
    content = "\n".join(lines).strip()
    return content or None


# ── writers ───────────────────────────────────────────────────────────────────

def _write_env(keys: dict[str, str]) -> None:
    env_path = Path(".env")
    existing: dict[str, str] = {}
    if env_path.exists():
        for line in env_path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, v = line.split("=", 1)
                existing[k.strip()] = v.strip()
    existing.update(keys)
    lines = ["# Generated by setup.py", ""]
    for k, v in existing.items():
        lines.append(f"{k}={v}")
    env_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _write_config(app_name: str, llm: dict, kbs: list[dict]) -> None:
    config: dict = {
        "app": {"name": app_name, "host": "0.0.0.0", "port": 8002, "cors_origins": ["*"]},
        "llm": llm,
        "embeddings": {"model": "BAAI/bge-m3", "device": "auto"},
        "retrieval": {"faiss_k": 8, "rerank_top_k": 3},
        "reranker": {
            "model": "BAAI/bge-reranker-v2-minicpm-layerwise",
            "cutoff_layers": [28],
            "use_fp16": True,
            "batch_size": 16,
        },
        "knowledge_bases": kbs,
        "tools": {"disabled_plugins": []},
        "memory": {"max_messages": 10},
        "logging": {"level": "INFO", "dir": "logs", "retention_days": 7},
        "system_prompt_path": "config/system_prompt.txt",
    }
    path = Path("config/config.yaml")
    path.parent.mkdir(exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        yaml.dump(config, f, allow_unicode=True, default_flow_style=False, sort_keys=False)


# ── main ─────────────────────────────────────────────────────────────────────

def main() -> None:
    print("╔══════════════════════════════════════════════╗")
    print("║       Pulse RAG  ─  Setup Wizard             ║")
    print("╚══════════════════════════════════════════════╝")

    _section("App")
    app_name = _ask("App name", "My RAG Assistant")

    _section("LLM")
    llm = _collect_llm()

    _section("API Keys")
    api_keys = _collect_api_keys()

    _section("Knowledge Bases")
    kbs = _collect_knowledge_bases()

    _section("System Prompt")
    prompt_text = _collect_system_prompt()

    print("\n─── Summary " + "─" * 40)
    print(f"  App  : {app_name}")
    print(f"  LLM  : {llm['provider']} / {llm['model']}")
    print(f"  KBs  : {len(kbs)} ({', '.join(k['name'] for k in kbs)})")
    if api_keys:
        print(f"  Keys : {', '.join(api_keys)}")

    if not _ask_yn("\nWrite these settings?", True):
        print("Aborted — nothing written.")
        return

    print("\nWriting files…")
    if api_keys:
        _write_env(api_keys)
        print("  ✓ .env")
    _write_config(app_name, llm, kbs)
    print("  ✓ config/config.yaml")
    if prompt_text:
        p = Path("config/system_prompt.txt")
        p.parent.mkdir(exist_ok=True)
        p.write_text(prompt_text, encoding="utf-8")
        print("  ✓ config/system_prompt.txt")

    print("\nSetup complete!")
    if kbs and _ask_yn("\nBuild FAISS index now?", True):
        subprocess.run([sys.executable, "scripts/build_index.py"], check=False)
    print("\nStart the server:  python main.py")


if __name__ == "__main__":
    main()
